from __future__ import annotations

from typing import Literal


AssuranceState = Literal[
    "PASSIVE_ARTIFACT_VERIFIED",
    "READ_ONLY_RUNTIME_VERIFIED",
    "BOUNDED_EXECUTION_VERIFIED",
    "MUTATION_WITH_ROLLBACK_VERIFIED",
    "LIVE_PROVIDER_VERIFIED",
    "DEMO_ONLY_VERIFIED",
    "BLOCKED_BY_EVIDENCE",
    "SAFETY_CRITICAL_PROHIBITED",
]

PASSIVE_ARTIFACT_VERIFIED: AssuranceState = "PASSIVE_ARTIFACT_VERIFIED"
READ_ONLY_RUNTIME_VERIFIED: AssuranceState = "READ_ONLY_RUNTIME_VERIFIED"
BOUNDED_EXECUTION_VERIFIED: AssuranceState = "BOUNDED_EXECUTION_VERIFIED"
MUTATION_WITH_ROLLBACK_VERIFIED: AssuranceState = "MUTATION_WITH_ROLLBACK_VERIFIED"
LIVE_PROVIDER_VERIFIED: AssuranceState = "LIVE_PROVIDER_VERIFIED"
DEMO_ONLY_VERIFIED: AssuranceState = "DEMO_ONLY_VERIFIED"
BLOCKED_BY_EVIDENCE: AssuranceState = "BLOCKED_BY_EVIDENCE"
SAFETY_CRITICAL_PROHIBITED: AssuranceState = "SAFETY_CRITICAL_PROHIBITED"

ASSURANCE_STATES: tuple[AssuranceState, ...] = (
    PASSIVE_ARTIFACT_VERIFIED,
    READ_ONLY_RUNTIME_VERIFIED,
    BOUNDED_EXECUTION_VERIFIED,
    MUTATION_WITH_ROLLBACK_VERIFIED,
    LIVE_PROVIDER_VERIFIED,
    DEMO_ONLY_VERIFIED,
    BLOCKED_BY_EVIDENCE,
    SAFETY_CRITICAL_PROHIBITED,
)


def is_assurance_state(value: object) -> bool:
    return value in ASSURANCE_STATES
