from dataclasses import dataclass

# Standard authority tiers
TIER_0 = "Tier 0 — read-only inspection"
TIER_1 = "Tier 1 — artifact-only planning/validation"
TIER_2 = "Tier 2 — operator-managed setup/runtime helper"
TIER_3 = "Tier 3 — HITL-gated execution candidate"
TIER_4 = "Tier 4 — forbidden/unpromoted automation"

VALID_TIERS = {TIER_0, TIER_1, TIER_2, TIER_3, TIER_4}

# Valid promotion states
STATE_SPEC_ONLY = "spec_only"
STATE_ARTIFACT_ONLY = "artifact_only"
STATE_VALIDATION_ONLY = "validation_only"
STATE_READ_ONLY_RUNTIME_CANDIDATE = "read_only_runtime_candidate"
STATE_OPERATOR_MANAGED = "operator_managed"
STATE_HITL_RUNTIME_CANDIDATE = "hitl_runtime_candidate"
STATE_FORBIDDEN_UNPROMOTED = "forbidden_unpromoted"
STATE_ENABLED = "enabled"

VALID_PROMOTION_STATES = {
    STATE_SPEC_ONLY,
    STATE_ARTIFACT_ONLY,
    STATE_VALIDATION_ONLY,
    STATE_READ_ONLY_RUNTIME_CANDIDATE,
    STATE_OPERATOR_MANAGED,
    STATE_HITL_RUNTIME_CANDIDATE,
    STATE_FORBIDDEN_UNPROMOTED,
    STATE_ENABLED,
}

# Valid approval modes
MODE_NONE = "none"
MODE_EXPLICIT_OPERATOR_INVOCATION = "explicit_operator_invocation"
MODE_HITL_ARTIFACT_REQUIRED = "hitl_artifact_required"
MODE_FORBIDDEN_UNPROMOTED = "forbidden_unpromoted"

VALID_APPROVAL_MODES = {
    MODE_NONE,
    MODE_EXPLICIT_OPERATOR_INVOCATION,
    MODE_HITL_ARTIFACT_REQUIRED,
    MODE_FORBIDDEN_UNPROMOTED,
}


@dataclass(frozen=True)
class CommandAuthorityRecord:
    name: str  # Script name or subcommand path, e.g. "builder" or "builder-session prepare-package"
    entrypoint: str  # Python entrypoint mapping
    tier: str  # Authority tier
    promotion_state: str  # Capability promotion state
    runtime_boundary: str  # Description of execution boundaries
    write_boundary: str  # Description of what may be modified or created
    approval_mode: str  # Method of approval required
    approval_boundary: str  # Human boundary for approval
    output_behavior: str  # Behavior of stdout/stderr and file writing
    failure_mode: str  # How errors are propagated and state recovered
    notes: str  # Details on limitations and deprecated/legacy logic
    allows_runtime_start: bool = False
    allows_model_execution: bool = False
    allows_shell_execution: bool = False
    allows_source_writes: bool = False
    allows_memory_mutation: bool = False
    allows_git_mutation: bool = False
    allows_artifact_writes: bool = False
    allows_state_writes: bool = False
    allows_readonly_subprocess: bool = False
    allows_external_tool_invocation: bool = False

    @property
    def is_command_group(self) -> bool:
        return self.name in (
            "builder",
            "builder-context",
            "builder-goose",
            "builder-deepagents",
            "builder-hitl",
            "builder-orchestration",
            "builder-session",
            "builder-profile-pack",
            "builder-workflow",
            "builder-ledger",
            "builder-targets",
            "builder-platform",
            "builder-config",
            "builder-setup",
        )

    @property
    def authority_delegates_to_subcommands(self) -> bool:
        return self.is_command_group


# A curated list of subcommands that must be explicitly classified
REQUIRED_SUBCOMMANDS = {
    "builder-targets list",
    "builder-targets show",
    "builder-targets validate",
    "builder-targets artifact",
    "builder-targets demo",
    "builder-targets readonly-founder-demo",
    "builder-session prepare-package",
    "builder-session validate-prepare-package",
    "builder-session summarize-prepare-package",
    "builder-context pack",
    "builder-context changed",
    "builder-context artifact",
    "builder start",
    "builder ask",
    "builder verify",
    "builder-goose manifest",
    "builder-goose validate",
    "builder-goose readonly-audit",
    "builder-goose validate-audit",
    "builder-goose inspect-readonly",
    "builder-goose validate-inspection",
    "builder-goose start-readonly",
    "builder-deepagents policy",
    "builder-deepagents validate",
    "builder-deepagents readiness",
    "builder-deepagents validate-readiness",
    "builder-deepagents delegate",
    "builder-deepagents work-plan",
    "builder-deepagents assign-subagent",
    "builder-deepagents record-result",
    "builder-deepagents review-result",
    "builder-deepagents request-human-gate",
    "builder-deepagents record-blocked-action",
    "builder-deepagents proposal-result",
    "builder-deepagents validate-work-artifact",
    "builder-hitl request",
    "builder-hitl receipt",
    "builder-hitl validate",
    "builder-hitl promotion-request",
    "builder-hitl promotion-review",
    "builder-hitl promotion-decision",
    "builder-hitl approval-boundary",
    "builder-hitl rejection-record",
    "builder-hitl validate-promotion",
    "builder-hitl candidate-manifest",
    "builder-hitl validate-candidate-manifest",
    "builder-orchestration plan",
    "builder-orchestration render-assignment",
    "builder-orchestration validate",
    "builder-orchestration dry-run",
    "builder-profile-pack scaffold",
    "builder-profile-pack render",
    "builder-profile-pack validate",
    "builder-profile-pack dry-run",
    "builder-model-policy validate",
    "builder-model-policy render",
    "builder-model-policy dry-run",
    "builder workflow plan",
    "builder workflow promote",
    "builder workflow candidate",
    "builder workflow verify-chain",
    "builder workflow handoff",
    "builder workflow status",
    "builder ledger list",
    "builder ledger replay",
    "builder ledger audit",
    "builder ledger export",
    "builder-workflow plan",
    "builder-workflow promote",
    "builder-workflow candidate",
    "builder-workflow verify-chain",
    "builder-workflow handoff",
    "builder-workflow status",
    "builder-ledger list",
    "builder-ledger replay",
    "builder-ledger audit",
    "builder-ledger export",
    "builder-platform matrix",
    "builder-platform status",
    "builder-platform audit-docs",
    "builder-config schema",
    "builder-config resolve",
    "builder-config validate",
    "builder-setup plan",
    "builder-setup validate-plan",
}

COMMAND_AUTHORITY_REGISTRY: tuple[CommandAuthorityRecord, ...] = (
    # --- Top-Level Script Entrypoints (Delegating to subcommands) ---
    CommandAuthorityRecord(
        name="builder",
        entrypoint="builder_ii.cli:app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Delegates to helper subcommands; root CLI does not execute direct agent/model loops.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Operator must explicitly run command options from active terminal.",
        output_behavior="Interactive terminal messages, text reports, or dispatch to subcommands.",
        failure_mode="Exits non-zero with diagnostic logs; leaves target system unchanged.",
        notes="Root command of builder-II developer platform. Delegates execution to subcommands.",
    ),
    CommandAuthorityRecord(
        name="builder-runtime",
        entrypoint="builder_ii.runtime_control:runtime_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Interacts with local server endpoints, background agents, and runtime indicators.",
        write_boundary="Writes session runtime lockfiles and state indicators locally.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Operator must trigger control signals manually.",
        output_behavior="Prints server status and active process logs to stdout.",
        failure_mode="Reports failure to talk to the local background process; exits non-zero.",
        notes="Inspects and controls runtime agent sessions locally.",
        allows_runtime_start=True,
        allows_state_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-lanes",
        entrypoint="builder_ii.lane_guides:lane_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Evaluates passive rules and checklists; no subprocess execution.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="Passive check, no approval required.",
        output_behavior="Prints verification checklists and audit messages to console.",
        failure_mode="Exits non-zero if validation fails.",
        notes="Guides operator lane readiness before committing artifacts.",
    ),
    CommandAuthorityRecord(
        name="builder-tools",
        entrypoint="builder_ii.tools_cli:tools_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Lists or verifies tool specs; can query tool registry metadata.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Operator runs spec auditing.",
        output_behavior="Prints JSON tool definitions and compatibility maps.",
        failure_mode="Exits non-zero if schema validations fail.",
        notes="Audits tools schema definitions.",
    ),
    CommandAuthorityRecord(
        name="builder-context",
        entrypoint="builder_ii.context_cli:context_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Legacy context builder; delegates execution details to subcommands.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Legacy context generator; operator must run command explicitly.",
        output_behavior="Generates codebase context state representation via subcommands.",
        failure_mode="Exits non-zero if git or file scanning fails.",
        notes="LEGACY. Uses external repomix or git commands. Not the canonical governed path.",
    ),
    CommandAuthorityRecord(
        name="builder-git-state",
        entrypoint="builder_ii.git_state_cli:git_state_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Executes local git queries via read-only subprocess.",
        write_boundary="Writes declarative state file artifacts in workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="Passive git branch check.",
        output_behavior="Saves JSON file containing current commit info.",
        failure_mode="Exits non-zero if git command fails.",
        notes="Captures current revision state to confirm context stability.",
        allows_artifact_writes=True,
        allows_readonly_subprocess=True,
    ),
    CommandAuthorityRecord(
        name="builder-targets",
        entrypoint="builder_ii.targets_cli:targets_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Delegates target operations to helper subcommands; root CLI does not execute direct agent loops.",
        write_boundary="No direct write authority at root targets CLI level.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Operator must explicitly run command options from active terminal.",
        output_behavior="Interactive terminal messages or dispatch to subcommands.",
        failure_mode="Exits non-zero on target resolution error.",
        notes="Root command of targets CLI.",
    ),
    CommandAuthorityRecord(
        name="builder-targets list",
        entrypoint="builder_ii.targets_cli:targets_app",
        tier=TIER_0,
        promotion_state=STATE_SPEC_ONLY,
        runtime_boundary="Retrieves target profile metadata list; no execution.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs available target names and definitions.",
        failure_mode="Exits non-zero on target resolution error.",
        notes="Lists profiles like generic, builder, and core.",
    ),
    CommandAuthorityRecord(
        name="builder-targets show",
        entrypoint="builder_ii.targets_cli:targets_app",
        tier=TIER_0,
        promotion_state=STATE_SPEC_ONLY,
        runtime_boundary="Retrieves target profile details; no execution.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs detailed target configuration.",
        failure_mode="Exits non-zero on target resolution error.",
        notes="Shows profile like generic, builder, and core.",
    ),
    CommandAuthorityRecord(
        name="builder-targets validate",
        entrypoint="builder_ii.targets_cli:targets_app",
        tier=TIER_0,
        promotion_state=STATE_SPEC_ONLY,
        runtime_boundary="Validates target profile registry or artifact.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs validation success or errors.",
        failure_mode="Exits non-zero on validation failure.",
        notes="Validates target configuration files.",
    ),
    CommandAuthorityRecord(
        name="builder-targets artifact",
        entrypoint="builder_ii.targets_cli:targets_app",
        tier=TIER_1,
        promotion_state=STATE_SPEC_ONLY,
        runtime_boundary="Resolves target details without execution.",
        write_boundary="Writes target profile JSON artifact to path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs JSON target artifact or writes to file.",
        failure_mode="Exits non-zero on generation errors.",
        notes="Generates target profile artifacts.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-targets demo",
        entrypoint="builder_ii.targets_cli:targets_app",
        tier=TIER_0,
        promotion_state=STATE_SPEC_ONLY,
        runtime_boundary="Retrieves target profile demo recipe; no execution.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs markdown demo recipe.",
        failure_mode="Exits non-zero on target resolution error.",
        notes="Prints target profile demo command recipes.",
    ),
    CommandAuthorityRecord(
        name="builder-targets readonly-founder-demo",
        entrypoint="builder_ii.targets_cli:targets_app",
        tier=TIER_1,
        promotion_state=STATE_SPEC_ONLY,
        runtime_boundary="Generates passive read-only founder demo planning artifacts; no execution.",
        write_boundary="Writes demo artifacts, events, and status JSON files in output directory.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs list of generated files.",
        failure_mode="Exits non-zero on generation errors.",
        notes="Emits only passive planning artifacts with zero execution authority.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-session",
        entrypoint="builder_ii.session_cli:session_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Delegates packaging and checks to subcommands.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_NONE,
        approval_boundary="Read-only checks or artifact-only packaging; no approval needed.",
        output_behavior="Dispatches to subcommand functions.",
        failure_mode="Raises ValidationError or exits non-zero on corrupt schemas.",
        notes="Canonical governed operator lane entrypoint.",
    ),
    CommandAuthorityRecord(
        name="builder-agent",
        entrypoint="builder_ii.agent_cli:agent_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Resolves active agent profiles and manifests.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Operator triggers agent inventory check.",
        output_behavior="Lists matching agent definitions.",
        failure_mode="Exits non-zero if spec parse fails.",
        notes="Verifies agent metadata without starting active sessions.",
    ),
    CommandAuthorityRecord(
        name="builder-bridge",
        entrypoint="builder_ii.bridge_cli:bridge_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Tests readiness of external deepagents integrations.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Operator checks network bridge connectivity.",
        output_behavior="Outputs status report of endpoints.",
        failure_mode="Exits non-zero if network connection fails.",
        notes="Used for bridge diagnostics.",
    ),
    CommandAuthorityRecord(
        name="builder-bundle",
        entrypoint="builder_ii.bundle_cli:bundle_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Validates bundle definitions or packages build artifacts.",
        write_boundary="Creates ZIP or tar bundles in designated build folder.",
        approval_mode=MODE_NONE,
        approval_boundary="Artifact build task.",
        output_behavior="Saves packed bundles.",
        failure_mode="Fails build process and reports missing manifest files.",
        notes="Packages bundle content cleanly.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-goose",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Delegates validation and read-only audits to subcommands.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_NONE,
        approval_boundary="Validation and audit only.",
        output_behavior="Dispatches to validation subcommand functions.",
        failure_mode="Exits non-zero on verification failure.",
        notes="Interacts with Goose session metadata and configurations.",
    ),
    CommandAuthorityRecord(
        name="builder-records",
        entrypoint="builder_ii.approval_records_cli:approval_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Decodes and validates cryptographically signed or structured approval logs.",
        write_boundary="Writes verified signature files.",
        approval_mode=MODE_NONE,
        approval_boundary="None; read-only verification.",
        output_behavior="Prints verification results.",
        failure_mode="Exits non-zero on signature mismatch.",
        notes="Governance record validator.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-preflight",
        entrypoint="builder_ii.preflight_cli:preflight_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Runs local environment checks (Python version, CLI presence).",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Lists check statuses.",
        failure_mode="Exits non-zero on system incompatibility.",
        notes="Preflight sanity checker.",
    ),
    CommandAuthorityRecord(
        name="builder-receipt",
        entrypoint="builder_ii.receipt_records_cli:receipt_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Generates or reads execution receipts.",
        write_boundary="Writes receipt JSON files to output folders.",
        approval_mode=MODE_NONE,
        output_behavior="Saves JSON data.",
        failure_mode="Exits non-zero on bad receipt schema.",
        approval_boundary="None.",
        notes="Tracks execution history.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-chain",
        entrypoint="builder_ii.chain_summary_cli:chain_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Traces artifact lineage chains.",
        write_boundary="Writes chain validation artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Generates validation chain report.",
        failure_mode="Exits non-zero if lineage broken.",
        notes="Artifact linkage audit.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-handoff",
        entrypoint="builder_ii.handoff_bundle_cli:handoff_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Aggregates verified evidence and creates handoff bundle metadata.",
        write_boundary="Writes handoff markdown files.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes handoff bundle files.",
        failure_mode="Exits non-zero on missing verification docs.",
        notes="Packages handoffs.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-intake",
        entrypoint="builder_ii.intake_cli:intake_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Ingests inputs from outside workspace.",
        write_boundary="Writes configuration files in specific workspace location.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Saves ingested assets.",
        failure_mode="Exits non-zero on invalid payload.",
        notes="Imports data packages.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-index",
        entrypoint="builder_ii.artifact_index_cli:index_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Tracks and indexes generated artifact files.",
        write_boundary="Updates local artifact index JSON ledger.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Updates local index file.",
        failure_mode="Exits non-zero if path outside worktree.",
        notes="Passive registry of workspace outputs.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-promotion",
        entrypoint="builder_ii.promotion_readiness_cli:promotion_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Analyzes readiness for target promotion.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs promotion validation list.",
        failure_mode="Exits non-zero if promotion checklist is not met.",
        notes="Validates readiness gates.",
    ),
    CommandAuthorityRecord(
        name="builder-promotion-decision",
        entrypoint="builder_ii.promotion_decision_cli:promotion_decision_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Creates a signed promotion decision artifact.",
        write_boundary="Writes promotion decision JSON artifact.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes signed promotion records.",
        failure_mode="Exits non-zero on schema validation failures.",
        notes="Governance promotion decision recorder.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-state-index",
        entrypoint="builder_ii.state_index_cli:state_index_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Constructs system state summaries.",
        write_boundary="Writes state index JSON files.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs state summary records.",
        failure_mode="Exits non-zero on file-system index failures.",
        notes="Indexes state layers.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-snapshot",
        entrypoint="builder_ii.snap_cli:snap_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Records current directory snapshot hashes.",
        write_boundary="Writes workspace snapshot hash index.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Generates checksum manifest.",
        failure_mode="Exits non-zero on scanning error.",
        notes="Workspace integrity checks.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_4,
        promotion_state=STATE_FORBIDDEN_UNPROMOTED,
        runtime_boundary="Delegates deepagent specs rendering and validation to subcommands; active run is forbidden.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_FORBIDDEN_UNPROMOTED,
        approval_boundary="Forbidden; no supported approval path.",
        output_behavior="Dispatches to subcommands.",
        failure_mode="Exits non-zero.",
        notes="Optional readiness specs and dry-runs only. Autonomous runs are blocked.",
    ),
    CommandAuthorityRecord(
        name="builder-notes",
        entrypoint="builder_ii.notes_cli:notes_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Verifies or creates handoff notes artifacts.",
        write_boundary="Writes handoff notes markdown files.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes text files.",
        failure_mode="Exits non-zero if handoff validations fail.",
        notes="Writes handoff notes.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-quality",
        entrypoint="builder_ii.quality_cli:quality_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Checks code linting or test coverage thresholds.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints compliance report.",
        failure_mode="Exits non-zero if quality threshold missed.",
        notes="Quality assurance checks.",
    ),
    CommandAuthorityRecord(
        name="builder-research",
        entrypoint="builder_ii.research_cli:research_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Builds read-only research plans.",
        write_boundary="Writes plan metadata files.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs JSON research plan.",
        failure_mode="Exits non-zero on validation failures.",
        notes="Artifact planning utility.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-performance",
        entrypoint="builder_ii.performance_cli:performance_app",
        tier=TIER_0,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Measures CLI loading time and file sizes.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs timing statistics.",
        failure_mode="Exits non-zero if execution limits exceeded.",
        notes="Performance benchmarking.",
    ),
    CommandAuthorityRecord(
        name="builder-readonly",
        entrypoint="builder_ii.readonly_inspection_cli:readonly_app",
        tier=TIER_0,
        promotion_state=STATE_READ_ONLY_RUNTIME_CANDIDATE,
        runtime_boundary="Inspects system files and configurations without execution.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs inspection reports.",
        failure_mode="Exits non-zero if targeted file does not exist.",
        notes="Ensures safe environment observation.",
    ),
    CommandAuthorityRecord(
        name="builder-verification",
        entrypoint="builder_ii.verification_cli:verification_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates verification profile schemas.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs verification lists.",
        failure_mode="Exits non-zero if profiles are malformed.",
        notes="Audits verification setups.",
    ),
    CommandAuthorityRecord(
        name="builder-hitl",
        entrypoint="builder_ii.hitl_execution_cli:hitl_app",
        tier=TIER_3,
        promotion_state=STATE_HITL_RUNTIME_CANDIDATE,
        runtime_boundary="Delegates execution request and receipt operations to subcommands.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_HITL_ARTIFACT_REQUIRED,
        approval_boundary="Operator must sign hitl request and verify receipts.",
        output_behavior="Dispatches to subcommands.",
        failure_mode="Exits non-zero on signature or verification failure.",
        notes="HITL-gated candidate tracking.",
    ),
    CommandAuthorityRecord(
        name="builder-orchestration",
        entrypoint="builder_ii.orchestration_cli:orchestration_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Delegates passive plan setup, assignment rendering, validation, and dry-run subcommands.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Dispatches to subcommands.",
        failure_mode="Exits non-zero on schema validation failures.",
        notes="Artifact orchestration and assignment planner; no runtime or execution authority.",
    ),
    CommandAuthorityRecord(
        name="builder-profile-pack",
        entrypoint="builder_ii.profile_pack_cli:profile_pack_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Delegates passive profile-pack scaffold, render, dry-run, and validation subcommands.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Dispatches to profile-pack artifact lifecycle subcommands.",
        failure_mode="Exits non-zero on schema or governance validation failures.",
        notes="Passive profile-pack lifecycle; no runtime, model, Goose, deepagents, MCP, shell, or verification execution.",
    ),
    CommandAuthorityRecord(
        name="builder-model-policy",
        entrypoint="builder_ii.model_policy_cli:model_policy_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Delegates passive model client registry and routing policy subcommands.",
        write_boundary="No direct write authority at root CLI level.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Dispatches to model policy artifact validation, rendering, and dry-run subcommands.",
        failure_mode="Exits non-zero on schema validation failures.",
        notes="Passive model routing metadata; never invokes models or provider endpoints.",
    ),
    CommandAuthorityRecord(
        name="builder-platform",
        entrypoint="builder_ii.platform_status_cli:platform_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Delegates passive completion-truth matrix, status, and docs-audit rendering; no runtime, model, shell, Goose, deepagents, MCP, or tool execution.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Dispatches to truth rendering and validation subcommands.",
        failure_mode="Exits non-zero on invalid matrix metadata, missing authority coverage, or false-completion docs claims.",
        notes="R0 truth machine command group. It reports platform state and cannot promote authority.",
    ),
    CommandAuthorityRecord(
        name="builder-config",
        entrypoint="builder_ii.config_cli:config_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Delegates passive config schema rendering, source resolution, and validation; no runtime, model, shell, Goose, deepagents, MCP, tool, or patch execution.",
        write_boundary="No direct write authority at root CLI level; subcommands may write explicit JSON artifacts only when --output is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Dispatches to schema, resolve, and validate subcommands.",
        failure_mode="Exits non-zero on invalid config artifacts, unsafe path policy, or unsupported source values.",
        notes="R1.1 passive config source surface. Metadata is not runtime permission.",
    ),
    CommandAuthorityRecord(
        name="builder-setup",
        entrypoint="builder_ii.setup_cli:setup_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Delegates passive setup plan generation and validation; no setup apply, rollback, Goose start, model call, shell execution, deepagents runtime, MCP/tool invocation, or patch authority.",
        write_boundary="No direct write authority at root CLI level; plan writes only an explicit setup-plan JSON artifact when --output is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Dispatches to plan and validate-plan subcommands.",
        failure_mode="Exits non-zero on invalid resolution, unsafe path policy, or malformed setup plan artifacts.",
        notes="R1.1 passive setup planning only. Existing builder setup remains legacy/operator-managed until later R1 slices reconcile it.",
    ),
    CommandAuthorityRecord(
        name="builder-workflow",
        entrypoint="builder_ii.workflow_cli:workflow_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Delegates passive workflow state-machine subcommands; no runtime, model, shell, Goose, deepagents, or MCP execution.",
        write_boundary="Writes governed workflow artifacts only under explicit workflow output directories.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Dispatches to workflow plan, promotion, candidate, chain, handoff, and status subcommands.",
        failure_mode="Exits non-zero on stale stage, invalid schema, missing refs, or failed replay.",
        notes="Governed passive workflow orchestrator; records transitions and events without granting authority.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-ledger",
        entrypoint="builder_ii.ledger_cli:ledger_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Delegates event-ledger list, replay, audit, and export subcommands without executing runtime work.",
        write_boundary="Writes replay and ledger export artifacts only when requested by ledger subcommands.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints JSON audit/replay data or writes explicit ledger artifacts.",
        failure_mode="Exits non-zero on missing session, invalid replay, or missing artifact SHA reference.",
        notes="Event-sourced audit surface for governed workflow sessions.",
        allows_artifact_writes=True,
    ),
    # --- Selected Subcommands ---
    CommandAuthorityRecord(
        name="builder-session prepare-package",
        entrypoint="builder_ii.session_cli:session_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Prepares context packaging and checks files.",
        write_boundary="Writes prepared package files locally.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes packaged bundle files.",
        failure_mode="Exits non-zero if inputs malformed.",
        notes="Governed package preparation lane. Artifact-only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-session validate-prepare-package",
        entrypoint="builder_ii.session_cli:session_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Performs validations on the prepared package directory structure.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results.",
        failure_mode="Exits non-zero on validation error.",
        notes="Governed package validator.",
    ),
    CommandAuthorityRecord(
        name="builder-session summarize-prepare-package",
        entrypoint="builder_ii.session_cli:session_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Analyzes prepared package and generates a passive summary.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints package stats and content summaries.",
        failure_mode="Exits non-zero if read fails.",
        notes="Passive summary producer.",
    ),
    CommandAuthorityRecord(
        name="builder-context pack",
        entrypoint="builder_ii.context_cli:context_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Invokes legacy external scanner or git commands.",
        write_boundary="Writes context bundle files.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Explicit operator invocation only; no artifact approval chain.",
        output_behavior="Outputs packed context data.",
        failure_mode="Exits non-zero if repomix fails.",
        notes="Legacy repomix packing mode.",
        allows_artifact_writes=True,
        allows_external_tool_invocation=True,
    ),
    CommandAuthorityRecord(
        name="builder-context changed",
        entrypoint="builder_ii.context_cli:context_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Queries git status or git diff via subprocess.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Explicit operator invocation only; no artifact approval chain.",
        output_behavior="Outputs diff context.",
        failure_mode="Exits non-zero if git fails.",
        notes="Legacy git diff inspection mode.",
        allows_readonly_subprocess=True,
        allows_external_tool_invocation=True,
    ),
    CommandAuthorityRecord(
        name="builder-context artifact",
        entrypoint="builder_ii.context_cli:context_app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Processes codebase scanning, potentially using external tools like repomix.",
        write_boundary="Creates context artifact files.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Explicit operator invocation only; no artifact approval chain.",
        output_behavior="Writes context artifact to file.",
        failure_mode="Exits non-zero if scanner errors.",
        notes="Legacy repo scan. Avoid when builder-session prepare-package can be used.",
        allows_artifact_writes=True,
        allows_external_tool_invocation=True,
    ),
    CommandAuthorityRecord(
        name="builder start",
        entrypoint="builder_ii.cli:app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Starts background runtime processes and servers.",
        write_boundary="Creates process locks and configuration settings.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Explicit operator invocation only; no artifact approval chain.",
        output_behavior="Launches background process and writes log info.",
        failure_mode="Exits non-zero if server cannot start.",
        notes="Used to boot local agents or backends.",
        allows_runtime_start=True,
        allows_state_writes=True,
        allows_external_tool_invocation=True,
    ),
    CommandAuthorityRecord(
        name="builder ask",
        entrypoint="builder_ii.cli:app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Queries model provider or MLX local runtime using user input.",
        write_boundary="Writes conversation history files locally.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Explicit operator invocation only; no artifact approval chain.",
        output_behavior="Prints model response text to terminal.",
        failure_mode="Exits non-zero on API or local runtime error.",
        notes="Direct model chat surface.",
        allows_model_execution=True,
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder verify",
        entrypoint="builder_ii.cli:app",
        tier=TIER_2,
        promotion_state=STATE_OPERATOR_MANAGED,
        runtime_boundary="Invokes local pytest/runner test suites via subprocess.",
        write_boundary="No source code changes; generates test result files.",
        approval_mode=MODE_EXPLICIT_OPERATOR_INVOCATION,
        approval_boundary="Explicit operator invocation only; no artifact approval chain.",
        output_behavior="Outputs test run reports.",
        failure_mode="Exits non-zero if test cases fail.",
        notes="Audits repo testing state.",
        allows_readonly_subprocess=True,
        allows_external_tool_invocation=True,
    ),
    CommandAuthorityRecord(
        name="builder-goose manifest",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Inspects Goose configuration manifest templates.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Validates manifest layout.",
        failure_mode="Exits non-zero on schema mismatch.",
        notes="Goose spec validation.",
    ),
    CommandAuthorityRecord(
        name="builder-goose validate",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Performs validations on active Goose session configs.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs verification checklist status.",
        failure_mode="Exits non-zero on mismatch.",
        notes="Configuration verification.",
    ),
    CommandAuthorityRecord(
        name="builder-goose readonly-audit",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Ensures a target Goose session uses read-only tools only.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Validates tool capabilities and permissions.",
        failure_mode="Exits non-zero if write tools are allowed.",
        notes="Safety auditor for Goose profiles.",
    ),
    CommandAuthorityRecord(
        name="builder-goose validate-audit",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates the output of a Goose audit run.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results.",
        failure_mode="Exits non-zero on validation error.",
        notes="Audit integrity check.",
    ),
    CommandAuthorityRecord(
        name="builder-goose inspect-readonly",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Performs read-only inspection validation on explicitly requested paths.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Validates inspection path configuration.",
        failure_mode="Exits non-zero if write paths are targeted.",
        notes="Audit tool for read-only containment.",
    ),
    CommandAuthorityRecord(
        name="builder-goose validate-inspection",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates inspection config details.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results.",
        failure_mode="Exits non-zero on validation error.",
        notes="Validation check.",
    ),
    CommandAuthorityRecord(
        name="builder-goose start-readonly",
        entrypoint="builder_ii.goose_cli:goose_app",
        tier=TIER_4,
        promotion_state=STATE_FORBIDDEN_UNPROMOTED,
        runtime_boundary="Attempts to start a Goose session. Disabled and unpromoted by default.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_FORBIDDEN_UNPROMOTED,
        approval_boundary="Forbidden; no supported approval path.",
        output_behavior="Prints error block.",
        failure_mode="Exits non-zero.",
        notes="Starting active Goose runtime components from the platform is unpromoted.",
    ),
    CommandAuthorityRecord(
        name="builder-deepagents policy",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders governed deepagents policy metadata statically.",
        write_boundary="Writes policy JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Policy artifact rendering only; no deepagents construction.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents validate",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates deepagents spec metadata.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Validation checklist.",
        failure_mode="Exits non-zero on schema error.",
        notes="Dry-run audit.",
    ),
    CommandAuthorityRecord(
        name="builder-deepagents readiness",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders optional deepagents dependency-readiness metadata.",
        write_boundary="Writes readiness JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on readiness schema error.",
        notes="Readiness artifact only; does not construct agents or run delegation.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents validate-readiness",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates deepagents dependency-readiness metadata.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Validation checklist.",
        failure_mode="Exits non-zero on schema error.",
        notes="Readiness validation only.",
    ),
    CommandAuthorityRecord(
        name="builder-deepagents delegate",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_4,
        promotion_state=STATE_FORBIDDEN_UNPROMOTED,
        runtime_boundary="Attempts to execute autonomous models. Forbidden.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_FORBIDDEN_UNPROMOTED,
        approval_boundary="Forbidden; no supported approval path.",
        output_behavior="Error message.",
        failure_mode="Exits non-zero.",
        notes="Autonomous deepagent model execution is not promoted.",
    ),
    CommandAuthorityRecord(
        name="builder-deepagents work-plan",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive deepagents work plan statically.",
        write_boundary="Writes work plan JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Work plan rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents assign-subagent",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive subagent assignment statically.",
        write_boundary="Writes subagent assignment JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Subagent assignment rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents record-result",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive subagent result statically.",
        write_boundary="Writes subagent result JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Subagent result rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents review-result",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive subagent review statically.",
        write_boundary="Writes subagent review JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Subagent review rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents request-human-gate",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive human gate request statically.",
        write_boundary="Writes human gate request JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Human gate request rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents record-blocked-action",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive blocked action record statically.",
        write_boundary="Writes blocked action record JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Blocked action record rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents proposal-result",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive proposal result statically.",
        write_boundary="Writes proposal result JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Proposal result rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-deepagents validate-work-artifact",
        entrypoint="builder_ii.deepagents_cli:deepagents_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates passive deepagents work artifact metadata.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Validation checklist.",
        failure_mode="Exits non-zero on schema error.",
        notes="Validation audit only.",
    ),
    CommandAuthorityRecord(
        name="builder-hitl request",
        entrypoint="builder_ii.hitl_execution_cli:hitl_app",
        tier=TIER_3,
        promotion_state=STATE_HITL_RUNTIME_CANDIDATE,
        runtime_boundary="Collects and validates HITL request details.",
        write_boundary="Writes HITL request JSON artifact.",
        approval_mode=MODE_HITL_ARTIFACT_REQUIRED,
        approval_boundary="Requires explicit operator approval signature.",
        output_behavior="Writes JSON file.",
        failure_mode="Exits non-zero if required refs are missing.",
        notes="Prepares execution requests under HITL governance.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl receipt",
        entrypoint="builder_ii.hitl_execution_cli:hitl_app",
        tier=TIER_3,
        promotion_state=STATE_HITL_RUNTIME_CANDIDATE,
        runtime_boundary="Records execution completion or failure receipt metadata.",
        write_boundary="Writes HITL receipt JSON artifact.",
        approval_mode=MODE_HITL_ARTIFACT_REQUIRED,
        approval_boundary="Operator must sign hitl request and verify receipts.",
        output_behavior="Writes JSON file.",
        failure_mode="Exits non-zero on invalid request reference.",
        notes="Records governance confirmation without running code.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl validate",
        entrypoint="builder_ii.hitl_execution_cli:hitl_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates request and receipt artifact files against schema.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results.",
        failure_mode="Exits non-zero if malformed JSON or invalid schema.",
        notes="Audit validation utility.",
    ),
    CommandAuthorityRecord(
        name="builder-hitl promotion-request",
        entrypoint="builder_ii.hitl_promotion_cli:hitl_promotion_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive promotion request statically.",
        write_boundary="Writes promotion request JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Promotion request rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl promotion-review",
        entrypoint="builder_ii.hitl_promotion_cli:hitl_promotion_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive promotion review statically.",
        write_boundary="Writes promotion review JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Promotion review rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl promotion-decision",
        entrypoint="builder_ii.hitl_promotion_cli:hitl_promotion_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive promotion decision statically.",
        write_boundary="Writes promotion decision JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Promotion decision rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl approval-boundary",
        entrypoint="builder_ii.hitl_promotion_cli:hitl_promotion_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive approval boundary statically.",
        write_boundary="Writes approval boundary JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Approval boundary rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl rejection-record",
        entrypoint="builder_ii.hitl_promotion_cli:hitl_promotion_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive rejection record statically.",
        write_boundary="Writes rejection record JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Rejection record rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl validate-promotion",
        entrypoint="builder_ii.hitl_promotion_cli:hitl_promotion_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates passive promotion bridge artifact files against schema.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results.",
        failure_mode="Exits non-zero on schema error.",
        notes="Validation audit only.",
    ),
    CommandAuthorityRecord(
        name="builder-hitl candidate-manifest",
        entrypoint="builder_ii.hitl_execution_cli:hitl_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive execution candidate manifest statically.",
        write_boundary="Writes candidate manifest JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Writes JSON files.",
        failure_mode="Exits non-zero on format mismatch.",
        notes="Candidate manifest rendering only.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-hitl validate-candidate-manifest",
        entrypoint="builder_ii.hitl_execution_cli:hitl_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates passive candidate manifest and validation report files against schema.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results.",
        failure_mode="Exits non-zero on schema error.",
        notes="Validation audit only.",
    ),
    CommandAuthorityRecord(
        name="builder-orchestration plan",
        entrypoint="builder_ii.orchestration_cli:orchestration_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Creates plan structure statically without launching active agents.",
        write_boundary="Writes plan JSON file.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Outputs serialized orchestration plan.",
        failure_mode="Exits non-zero if target profile is invalid.",
        notes="Creates the plan under governance.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-orchestration render-assignment",
        entrypoint="builder_ii.orchestration_cli:orchestration_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive Goal 2 assignment and orchestration plans from existing source artifacts and SHA-256 refs.",
        write_boundary="Writes assignment/orchestration JSON only to explicit artifact output paths.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints or writes deterministic assignment and orchestration assignment plan artifacts.",
        failure_mode="Fails closed on missing refs, digest mismatches, invalid model recommendations, unsafe governance, or authority escalation.",
        notes="Render only; does not call models, execute tools, invoke Goose/deepagents/MCP, run shell, or mutate target repositories.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-orchestration validate",
        entrypoint="builder_ii.orchestration_cli:orchestration_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates v1 orchestration and Goal 2 assignment/orchestration artifacts.",
        write_boundary="Writes validation-report JSON only when an explicit output path is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results and can write passive validation reports for Goal 2 artifacts.",
        failure_mode="Exits non-zero if validation fails.",
        notes="Validation-only auditor; validation never grants execution authority.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-orchestration dry-run",
        entrypoint="builder_ii.orchestration_cli:orchestration_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Creates a passive dry-run explaining Goal 2 planned bindings without executing anything.",
        write_boundary="Writes dry-run JSON only to an explicit artifact output path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints or writes dry-run JSON with denied capabilities, required promotions, evidence expectations, and handoff expectations.",
        failure_mode="Exits non-zero if the source orchestration assignment plan is invalid or claims authority.",
        notes="Dry-run remains non-runtime and cannot call models, tools, Goose, deepagents, MCP, shell, network, verification, or target writes.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-profile-pack scaffold",
        entrypoint="builder_ii.profile_pack_cli:profile_pack_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Scaffolds passive profile-pack manifests from local source refs and hashes only.",
        write_boundary="Writes profile-pack manifest JSON only to an explicit artifact output path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints manifest JSON or writes it to the requested output file.",
        failure_mode="Exits non-zero if source refs are missing or generated manifest validation fails.",
        notes="No runtime, model, Goose, deepagents, MCP, shell, verification, target-repo, or git authority.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-profile-pack render",
        entrypoint="builder_ii.profile_pack_cli:profile_pack_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders a passive profile-pack render plan without materializing runtime behavior.",
        write_boundary="Writes render-plan JSON only to an explicit artifact output path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints render-plan JSON or writes it to the requested output file.",
        failure_mode="Exits non-zero on invalid manifests, unknown profile kinds, or authority leakage.",
        notes="Render means deterministic artifact planning only; no execution or authorization.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-profile-pack validate",
        entrypoint="builder_ii.profile_pack_cli:profile_pack_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates profile-pack lifecycle artifacts and can emit a passive validation report.",
        write_boundary="Writes validation-report JSON only when an explicit output path is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints validation errors or a validation report; exits non-zero on invalid subjects.",
        failure_mode="Fails closed on unknown artifact kinds, missing schema versions, duplicate ids, or boundary leaks.",
        notes="Validation does not execute, authorize, promote, or prove planned verification ran.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-profile-pack dry-run",
        entrypoint="builder_ii.profile_pack_cli:profile_pack_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Creates a passive dry-run artifact showing what would render without executing anything.",
        write_boundary="Writes dry-run JSON only to an explicit artifact output path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints dry-run JSON or writes it to the requested output file.",
        failure_mode="Exits non-zero if manifest/render-plan validation fails or dry-run boundaries are violated.",
        notes="Dry-run remains non-runtime and cannot start Goose, construct deepagents, call models, call MCP, or run verification.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-model-policy validate",
        entrypoint="builder_ii.model_policy_cli:model_policy_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates passive model client registry, routing policy, and recommendation artifacts.",
        write_boundary="Writes validation report JSON only when an explicit output path is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints verification results or writes report JSON; exits non-zero on invalid artifacts.",
        failure_mode="Fails closed on unknown artifact kinds, missing schemas, or boundary leaks.",
        notes="Audit validation only; never calls models or provider endpoints.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-model-policy render",
        entrypoint="builder_ii.model_policy_cli:model_policy_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders passive model routing recommendation artifacts from registry and policy metadata.",
        write_boundary="Writes recommendation JSON only to an explicit artifact output path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints recommendation JSON or writes it to requested output file.",
        failure_mode="Exits non-zero on invalid policy/registry metadata or unknown candidate IDs.",
        notes="Produces advisory recommendations without executing models or granting execution authority.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-model-policy dry-run",
        entrypoint="builder_ii.model_policy_cli:model_policy_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Performs a passive routing recommendation dry-run showing recommended models without executing anything.",
        write_boundary="Writes dry-run recommendation JSON only to an explicit artifact output path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints dry-run JSON or writes it to requested output file.",
        failure_mode="Exits non-zero on validation failures or if any candidate lacks risk classification.",
        notes="Dry-run remains non-runtime and cannot invoke models or network endpoints.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-platform matrix",
        entrypoint="builder_ii.platform_status_cli:platform_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Renders the static source-derived completion truth matrix as JSON after validating shape and authority references.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints JSON to stdout.",
        failure_mode="Exits non-zero if required rows, state labels, evidence refs, or command authority refs are invalid.",
        notes="Artifact-only truth rendering. It does not run verification, models, tools, Goose, deepagents, shell commands, or MCP calls.",
    ),
    CommandAuthorityRecord(
        name="builder-platform status",
        entrypoint="builder_ii.platform_status_cli:platform_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Summarizes the completion truth matrix without inspecting runtime systems or target repositories.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints concise human-readable platform truth state to stdout.",
        failure_mode="Exits non-zero if the matrix or command authority coverage is invalid.",
        notes="States that builder-II is passive-foundation-complete and operationally incomplete, and names R0 -> R1 -> B1.",
    ),
    CommandAuthorityRecord(
        name="builder-platform audit-docs",
        entrypoint="builder_ii.platform_status_cli:platform_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Scans README.md and docs/**/*.md for false operational-completion claims without invoking external tools.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints JSON docs-truth audit report to stdout.",
        failure_mode="Exits non-zero when docs imply operational completion for non-OPERATIONALLY_VERIFIED capabilities or contain known stale claims.",
        notes="Docs truth enforcement only. It cannot rewrite docs or promote runtime authority.",
    ),
    CommandAuthorityRecord(
        name="builder-config schema",
        entrypoint="builder_ii.config_cli:config_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Renders the static generic-first config schema; no runtime, model, shell, Goose, deepagents, MCP, tool, or patch execution.",
        write_boundary="Writes schema JSON only to an explicit artifact output path when --output is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints schema JSON and optionally writes the same artifact to the requested output path.",
        failure_mode="Exits non-zero only on output path write failure.",
        notes="R1.1 schema artifact only; it grants no setup, runtime, model, tool, MCP, Goose, deepagents, or patch authority.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-config resolve",
        entrypoint="builder_ii.config_cli:config_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Resolves passive config sources and validates path policy without running subprocesses or invoking runtime systems.",
        write_boundary="Writes resolution JSON only to an explicit artifact output path when --output is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints source resolution JSON and optionally writes the same artifact to the requested output path.",
        failure_mode="Exits non-zero on invalid values, unsafe artifact-root policy, unknown profiles, or output path write failure.",
        notes="Records source precedence and legacy aliases. It cannot call models, tools, MCP, Goose, deepagents, shell commands, or apply patches.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-config validate",
        entrypoint="builder_ii.config_cli:config_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates config schema or resolution artifacts without runtime, model, shell, Goose, deepagents, MCP, tool, or patch execution.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints validation report JSON to stdout.",
        failure_mode="Exits non-zero on malformed artifacts, digest drift, unsupported kinds, or invalid current resolution.",
        notes="Validation only; no setup writes, runtime construction, provider calls, or target repo mutation.",
    ),
    CommandAuthorityRecord(
        name="builder-setup plan",
        entrypoint="builder_ii.setup_cli:setup_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Creates a passive setup plan from resolved config; no setup apply, rollback, runtime start, model call, shell execution, Goose start, deepagents construction, MCP/tool invocation, or patch authority.",
        write_boundary="Writes setup plan JSON only to an explicit artifact output path when --output is supplied.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints setup plan JSON and optionally writes the same artifact to the requested output path.",
        failure_mode="Exits non-zero on invalid resolution, unsafe path policy, malformed plan, or output path write failure.",
        notes="Planned writes are descriptive only. R1.1 setup plans are artifact_is_authority=false and cannot mutate target repos or user Goose config.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-setup validate-plan",
        entrypoint="builder_ii.setup_cli:setup_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates a passive setup plan artifact without applying setup, rollback, Goose, deepagents, model, MCP/tool, shell, or patch behavior.",
        write_boundary="No changes to workspace.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints setup plan validation report JSON to stdout.",
        failure_mode="Exits non-zero on malformed plan, digest drift, authority claims, or embedded resolution errors.",
        notes="Validation only. A valid setup plan remains artifact_is_authority=false.",
    ),
    CommandAuthorityRecord(
        name="builder workflow plan",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Creates a passive governed workflow plan; no model, shell, Goose, deepagents, MCP, or target-repo execution.",
        write_boundary="Writes workflow session, profile, routing, orchestration, work-plan, event, replay, ledger, and status artifacts under the workflow output directory.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after writing passive artifacts.",
        failure_mode="Exits non-zero on invalid target, stale output directory, missing source refs, or schema failure.",
        notes="First stage of the governed workflow state machine.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder workflow promote",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Records passive HITL promotion artifacts only; does not authorize execution.",
        write_boundary="Writes promotion request, review, decision, approval-boundary, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after recording the promotion boundary.",
        failure_mode="Exits non-zero if the workflow is not at planned stage or promotion artifacts fail validation.",
        notes="Promotion here means candidate-design boundary only, not runtime approval.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder workflow candidate",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Records a passive execution candidate manifest without invoking commands.",
        write_boundary="Writes candidate manifest, validation report, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after candidate recording.",
        failure_mode="Exits non-zero if the workflow is not at promoted stage or refs are stale.",
        notes="Candidate manifest remains structural and cannot execute verification.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder workflow verify-chain",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates artifact index and chain refs without running external tools.",
        write_boundary="Writes artifact index, chain verification, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after chain verification.",
        failure_mode="Exits non-zero on unknown kind, invalid native schema, broken ref, digest mismatch, or stale stage.",
        notes="Chain verification validates evidence links only; it is not execution evidence.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder workflow handoff",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Writes passive handoff summaries after chain verification; no runtime activation.",
        write_boundary="Writes handoff note, golden-path summary, demo README, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after handoff creation.",
        failure_mode="Exits non-zero unless the workflow is chain_verified and all handoff artifacts validate.",
        notes="Handoff is review material, not authority.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder workflow status",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Replays workflow events to reconstruct status without executing runtime work.",
        write_boundary="Writes refreshed replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints replayed workflow status JSON.",
        failure_mode="Exits non-zero on invalid session, event sequence, previous-event mismatch, or replay failure.",
        notes="Status is derived from events, not mutable memory.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder ledger list",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Reads workflow event ledgers and reconstructs status summaries only.",
        write_boundary="Read-only ledger inspection; no workspace changes.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints JSON rows for known workflow sessions.",
        failure_mode="Returns an empty list when no ledgers exist; exits non-zero on malformed sessions.",
        notes="Inspection-only ledger listing.",
    ),
    CommandAuthorityRecord(
        name="builder ledger replay",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Replays event records deterministically without executing runtime work.",
        write_boundary="Writes replay report JSON to an explicit or default workflow artifact path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints replay report JSON.",
        failure_mode="Exits non-zero on missing session, invalid event order, skipped stage, or previous-event mismatch.",
        notes="Replay reconstructs status from events, not mutable status files.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder ledger audit",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Scans event subject refs for a requested artifact SHA; no execution.",
        write_boundary="Read-only ledger inspection; no workspace changes.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints JSON audit matches including who, what, when, why, status, evidence, and next transition.",
        failure_mode="Exits non-zero when no event references the requested artifact SHA.",
        notes="Audit-by-digest surface for workflow evidence.",
    ),
    CommandAuthorityRecord(
        name="builder ledger export",
        entrypoint="builder_ii.cli:app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Exports event ledger artifacts without runtime execution.",
        write_boundary="Writes event ledger export JSON to an explicit or default workflow artifact path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints exported ledger JSON or writes it to the requested output.",
        failure_mode="Exits non-zero on missing session or invalid ledger validation.",
        notes="Ledger export remains a passive artifact.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-workflow plan",
        entrypoint="builder_ii.workflow_cli:workflow_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Creates a passive governed workflow plan; no model, shell, Goose, deepagents, MCP, or target-repo execution.",
        write_boundary="Writes workflow session, profile, routing, orchestration, work-plan, event, replay, ledger, and status artifacts under the workflow output directory.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after writing passive artifacts.",
        failure_mode="Exits non-zero on invalid target, stale output directory, missing source refs, or schema failure.",
        notes="Standalone script equivalent of builder workflow plan.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-workflow promote",
        entrypoint="builder_ii.workflow_cli:workflow_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Records passive HITL promotion artifacts only; does not authorize execution.",
        write_boundary="Writes promotion request, review, decision, approval-boundary, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after recording the promotion boundary.",
        failure_mode="Exits non-zero if the workflow is not at planned stage or promotion artifacts fail validation.",
        notes="Standalone script equivalent of builder workflow promote.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-workflow candidate",
        entrypoint="builder_ii.workflow_cli:workflow_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Records a passive execution candidate manifest without invoking commands.",
        write_boundary="Writes candidate manifest, validation report, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after candidate recording.",
        failure_mode="Exits non-zero if the workflow is not at promoted stage or refs are stale.",
        notes="Standalone script equivalent of builder workflow candidate.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-workflow verify-chain",
        entrypoint="builder_ii.workflow_cli:workflow_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Validates artifact index and chain refs without running external tools.",
        write_boundary="Writes artifact index, chain verification, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after chain verification.",
        failure_mode="Exits non-zero on unknown kind, invalid native schema, broken ref, digest mismatch, or stale stage.",
        notes="Standalone script equivalent of builder workflow verify-chain.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-workflow handoff",
        entrypoint="builder_ii.workflow_cli:workflow_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Writes passive handoff summaries after chain verification; no runtime activation.",
        write_boundary="Writes handoff note, golden-path summary, demo README, transition, event, replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints workflow status JSON after handoff creation.",
        failure_mode="Exits non-zero unless the workflow is chain_verified and all handoff artifacts validate.",
        notes="Standalone script equivalent of builder workflow handoff.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-workflow status",
        entrypoint="builder_ii.workflow_cli:workflow_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Replays workflow events to reconstruct status without executing runtime work.",
        write_boundary="Writes refreshed replay, ledger, and status artifacts.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints replayed workflow status JSON.",
        failure_mode="Exits non-zero on invalid session, event sequence, previous-event mismatch, or replay failure.",
        notes="Standalone script equivalent of builder workflow status.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-ledger list",
        entrypoint="builder_ii.ledger_cli:ledger_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Reads workflow event ledgers and reconstructs status summaries only.",
        write_boundary="Read-only ledger inspection; no workspace changes.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints JSON rows for known workflow sessions.",
        failure_mode="Returns an empty list when no ledgers exist; exits non-zero on malformed sessions.",
        notes="Standalone script equivalent of builder ledger list.",
    ),
    CommandAuthorityRecord(
        name="builder-ledger replay",
        entrypoint="builder_ii.ledger_cli:ledger_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Replays event records deterministically without executing runtime work.",
        write_boundary="Writes replay report JSON to an explicit or default workflow artifact path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints replay report JSON.",
        failure_mode="Exits non-zero on missing session, invalid event order, skipped stage, or previous-event mismatch.",
        notes="Standalone script equivalent of builder ledger replay.",
        allows_artifact_writes=True,
    ),
    CommandAuthorityRecord(
        name="builder-ledger audit",
        entrypoint="builder_ii.ledger_cli:ledger_app",
        tier=TIER_1,
        promotion_state=STATE_VALIDATION_ONLY,
        runtime_boundary="Scans event subject refs for a requested artifact SHA; no execution.",
        write_boundary="Read-only ledger inspection; no workspace changes.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints JSON audit matches including who, what, when, why, status, evidence, and next transition.",
        failure_mode="Exits non-zero when no event references the requested artifact SHA.",
        notes="Standalone script equivalent of builder ledger audit.",
    ),
    CommandAuthorityRecord(
        name="builder-ledger export",
        entrypoint="builder_ii.ledger_cli:ledger_app",
        tier=TIER_1,
        promotion_state=STATE_ARTIFACT_ONLY,
        runtime_boundary="Exports event ledger artifacts without runtime execution.",
        write_boundary="Writes event ledger export JSON to an explicit or default workflow artifact path.",
        approval_mode=MODE_NONE,
        approval_boundary="None.",
        output_behavior="Prints exported ledger JSON or writes it to the requested output.",
        failure_mode="Exits non-zero on missing session or invalid ledger validation.",
        notes="Standalone script equivalent of builder ledger export.",
        allows_artifact_writes=True,
    ),
)


def get_all_records() -> tuple[CommandAuthorityRecord, ...]:
    """Return all registered CommandAuthorityRecord instances."""
    return COMMAND_AUTHORITY_REGISTRY


def get_command_record(name: str) -> CommandAuthorityRecord | None:
    """Find a record by its exact name."""
    for record in COMMAND_AUTHORITY_REGISTRY:
        if record.name == name:
            return record
    return None


def validate_registry_invariants() -> list[str]:
    """Validate all registry constraints and return a list of error strings if any fail."""
    errors = []
    for r in COMMAND_AUTHORITY_REGISTRY:
        # Tier check
        if r.tier not in VALID_TIERS:
            errors.append(f"Record '{r.name}' has invalid tier '{r.tier}'")

        # Promotion state check
        if r.promotion_state not in VALID_PROMOTION_STATES:
            errors.append(
                f"Record '{r.name}' has invalid promotion state '{r.promotion_state}'"
            )

        # Approval mode check
        if r.approval_mode not in VALID_APPROVAL_MODES:
            errors.append(
                f"Record '{r.name}' has invalid approval mode '{r.approval_mode}'"
            )

        # Missing required string check
        if not r.runtime_boundary.strip():
            errors.append(f"Record '{r.name}' is missing runtime boundary description")
        if not r.write_boundary.strip():
            errors.append(f"Record '{r.name}' is missing write boundary description")
        if not r.output_behavior.strip():
            errors.append(f"Record '{r.name}' is missing output behavior description")
        if not r.failure_mode.strip():
            errors.append(f"Record '{r.name}' is missing failure mode description")
        if not r.approval_boundary.strip():
            errors.append(f"Record '{r.name}' is missing approval boundary description")

        # Human approval requirements
        has_authority_flag = (
            r.allows_runtime_start
            or r.allows_model_execution
            or r.allows_shell_execution
            or r.allows_source_writes
            or r.allows_external_tool_invocation
        )
        if has_authority_flag:
            if r.approval_mode == MODE_NONE:
                errors.append(
                    f"Record '{r.name}' has authority flags enabled but approval mode is 'none'"
                )

        # Tier 0 constraints
        if r.tier == TIER_0:
            has_risky = (
                r.allows_runtime_start
                or r.allows_model_execution
                or r.allows_shell_execution
                or r.allows_source_writes
                or r.allows_memory_mutation
                or r.allows_git_mutation
                or r.allows_artifact_writes
                or r.allows_state_writes
                or r.allows_external_tool_invocation
            )
            if has_risky:
                errors.append(
                    f"Tier 0 record '{r.name}' claims forbidden execution/mutation authority"
                )

        # Tier 1 constraints
        if r.tier == TIER_1:
            has_forbidden_tier1 = (
                r.allows_runtime_start
                or r.allows_model_execution
                or r.allows_shell_execution
                or r.allows_source_writes
                or r.allows_memory_mutation
                or r.allows_git_mutation
                or r.allows_state_writes
                or r.allows_external_tool_invocation
            )
            if has_forbidden_tier1:
                errors.append(
                    f"Tier 1 record '{r.name}' claims forbidden execution/mutation authority"
                )

        # Contradiction check: write boundary text vs write flags
        wb_lower = r.write_boundary.lower()
        has_any_write = (
            r.allows_source_writes or r.allows_artifact_writes or r.allows_state_writes
        )
        if not has_any_write:
            # Should not claim active writes in description
            if (
                "write" in wb_lower
                and "no " not in wb_lower
                and "not " not in wb_lower
                and "without " not in wb_lower
                and "read-only" not in wb_lower
            ):
                errors.append(
                    f"Record '{r.name}' write boundary text describes writes but no write flags are set"
                )
        else:
            # Should not say "no changes" or "no modifications"
            if (
                "no changes" in wb_lower
                or "no modifications" in wb_lower
                or "no write" in wb_lower
            ):
                errors.append(
                    f"Record '{r.name}' write flags are enabled but write boundary text claims no writes/changes"
                )

        # Conflation check
        for field_val in (
            r.name,
            r.entrypoint,
            r.tier,
            r.promotion_state,
            r.runtime_boundary,
            r.write_boundary,
            r.approval_boundary,
            r.output_behavior,
            r.failure_mode,
            r.notes,
        ):
            if "CORE builder-II" in field_val or "CORE Builder-II" in field_val:
                errors.append(
                    f"Record '{r.name}' contains forbidden framing 'CORE builder-II'"
                )

    return errors


def render_registry_markdown_table() -> str:
    """Helper function to render the command registry into a Markdown table for docs."""
    lines = [
        "| Command Name | Tier | State | Runtime Boundary | Write Boundary | Approval Mode | Approval Boundary | Allows Shell | Allows Writes | Artifact Writes | State Writes |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in COMMAND_AUTHORITY_REGISTRY:
        shell_str = "Yes" if r.allows_shell_execution else "No"
        write_str = "Yes" if r.allows_source_writes else "No"
        art_str = "Yes" if r.allows_artifact_writes else "No"
        state_str = "Yes" if r.allows_state_writes else "No"
        lines.append(
            f"| `{r.name}` | {r.tier} | `{r.promotion_state}` | {r.runtime_boundary} | {r.write_boundary} | `{r.approval_mode}` | {r.approval_boundary} | {shell_str} | {write_str} | {art_str} | {state_str} |"
        )
    return "\n".join(lines)
