from __future__ import annotations

import json as json_lib
import re
from pathlib import Path
from typing import Any

from builder_ii.config import MODEL_ALIASES

MODEL_CLIENT_REGISTRY_KIND = "builder_ii.model_client_registry"
MODEL_CLIENT_REGISTRY_SCHEMA_VERSION = 1

KNOWN_PROVIDER_IDS = {
    "mlx_provider",
    "openai_stub_provider",
    "anthropic_stub_provider",
    "groq_provider",
    "xai_provider",
    "google_provider",
    "ollama_provider",
    "openai_provider",
    "anthropic_provider",
}
KNOWN_CLIENT_IDS = {
    "mlx_lm_client",
    "openai_compat_client",
    "anthropic_stub_client",
    "groq_client",
    "xai_client",
    "google_client",
    "ollama_client",
    "openai_client",
    "anthropic_client",
}
KNOWN_MODEL_IDS = {
    "mlx-community/Phi-4-mini-reasoning-4bit",
    "mlx-community/Qwen2.5-Coder-7B-Instruct-4bit",
    "mlx-community/gemma-4-e4b-it-4bit",
    "mlx-community/gemma-4-12B-it-4bit",
    "mlx-community/Meta-Llama-3.1-8B-Instruct-4bit",
    "mlx-community/codegeex4-all-9b-4bit",
    "mlx-community/Qwen2.5-Coder-14B-Instruct-4bit",
    "mlx-community/Qwen3-Coder-30B-A3B-Instruct-4bit",
    "mlx-community/DeepSeek-Coder-V2-Lite-Instruct-4bit",
    "llama-3.3-70b-versatile",
    "mixtral-8x7b-32768",
    "grok-2-1212",
    "grok-beta",
    "google/gemini-1.5-pro",
    "google/gemini-1.5-flash",
    "google/gemini-1.0-ultra",
    "google/gemini-3.5-flash",
    "google/gemini-3.1-pro-preview",
    "google/gemini-3.1-flash-lite",
    "google/gemini-3-flash-preview",
    "gemma4:e4b",
    "gemma4:e2b",
    "qwen3.5:2b",
    "qwen3.5:0.8b",
    "ibm/granite4.1:3b",
    "llama-3.1-8b-instant",
    "openai/gpt-oss-20b",
    "meta-llama/llama-4-scout-17b-16e-instruct",
    "openai/gpt-oss-120b",
    "qwen/qwen3-32b",
    "moonshotai/kimi-k2-instruct-0905",
    "grok-4.3",
    "grok-build-0.1",
    "grok-4.1-fast",
    "gpt-5.5",
    "gpt-5.5-pro",
    "gpt-5.4",
    "gpt-5.4-mini",
    "gpt-5.4-nano",
    "gpt-5.3-codex",
    "gpt-4o",
    "o3",
    "claude-fable-5",
    "claude-opus-4-8",
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-sonnet-5",
    "claude-sonnet-4-6",
    "claude-sonnet-4-5",
    "claude-haiku-4-5-20251001",
    "gpt-4o-stub",
}
ALLOWED_ENDPOINT_KINDS = {"local_mlx", "openai_compatible_local", "cloud_stub", "openai_compatible_cloud"}
ALLOWED_RISK_CLASSIFICATIONS = {"local_offline", "local_network", "cloud_external"}
ALLOWED_COST_CLASSES = {"free_local", "low", "medium", "high", "placeholder"}

_REF_NAME_RE = re.compile(r"^[A-Z0-9_]+$")


def _obsolete_default_client_records() -> list[dict[str, Any]]:
    return [
        {
            "provider_id": "mlx_provider",
            "provider_name": "MLX Local Runtime Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX LM Python Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/Qwen2.5-Coder-7B-Instruct-4bit",
            "model_name": "Qwen 2.5 Coder 7B 4bit",
            "model_family": "qwen2.5",
            "model_alias": "qwen-coder",
            "context_window": 32768,
            "max_input_tokens": 32768,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "placeholder", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": ["MLX_MODEL_PATH"],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "MLX Local Runtime Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX LM Python Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/Phi-3.5-mini-instruct-4bit",
            "model_name": "Phi 3.5 Mini Instruct 4bit",
            "model_family": "phi3",
            "model_alias": "phi-reasoning",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 4096,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "placeholder", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": ["MLX_MODEL_PATH"],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_stub_provider",
            "provider_name": "OpenAI Compatible Cloud Stub Provider",
            "client_id": "openai_compat_client",
            "client_name": "OpenAI Compatible HTTP Client",
            "endpoint_kind": "cloud_stub",
            "model_id": "gpt-4o-stub",
            "model_name": "GPT 4o Stub",
            "model_family": "gpt4",
            "model_alias": None,
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 16384,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": True,
            "risk_classification": "cloud_external",
            "cost_class": "placeholder",
            "price_metadata": {"unit": "placeholder", "input_cost": "placeholder", "output_cost": "placeholder"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "llama-3.1-8b-instant",
            "model_name": "llama-3.1-8b-instant",
            "model_family": "cloud",
            "model_alias": "groq-llama-instant",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "openai/gpt-oss-20b",
            "model_name": "openai/gpt-oss-20b",
            "model_family": "cloud",
            "model_alias": "groq-gpt-oss-20b",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "meta-llama/llama-4-scout-17b-16e-instruct",
            "model_name": "meta-llama/llama-4-scout-17b-16e-instruct",
            "model_family": "cloud",
            "model_alias": "groq-llama-scout",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "openai/gpt-oss-120b",
            "model_name": "openai/gpt-oss-120b",
            "model_family": "cloud",
            "model_alias": "groq-gpt-oss-120b",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "qwen/qwen3-32b",
            "model_name": "qwen/qwen3-32b",
            "model_family": "cloud",
            "model_alias": "groq-qwen3-32b",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "moonshotai/kimi-k2-instruct-0905",
            "model_name": "moonshotai/kimi-k2-instruct-0905",
            "model_family": "cloud",
            "model_alias": "groq-kimi-k2",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-4.3",
            "model_name": "grok-4.3",
            "model_family": "cloud",
            "model_alias": "grok-4.3",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-build-0.1",
            "model_name": "grok-build-0.1",
            "model_family": "cloud",
            "model_alias": "grok-build-0.1",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-4.1-fast",
            "model_name": "grok-4.1-fast",
            "model_family": "cloud",
            "model_alias": "grok-4.1-fast",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.5",
            "model_name": "gpt-5.5",
            "model_family": "cloud",
            "model_alias": "gpt-5.5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.5-pro",
            "model_name": "gpt-5.5-pro",
            "model_family": "cloud",
            "model_alias": "gpt-5.5-pro",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.4",
            "model_name": "gpt-5.4",
            "model_family": "cloud",
            "model_alias": "gpt-5.4",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.4-mini",
            "model_name": "gpt-5.4-mini",
            "model_family": "cloud",
            "model_alias": "gpt-5.4-mini",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.4-nano",
            "model_name": "gpt-5.4-nano",
            "model_family": "cloud",
            "model_alias": "gpt-5.4-nano",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.3-codex",
            "model_name": "gpt-5.3-codex",
            "model_family": "cloud",
            "model_alias": "gpt-5.3-codex",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-4o",
            "model_name": "gpt-4o",
            "model_family": "cloud",
            "model_alias": "gpt-4o",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "o3",
            "model_name": "o3",
            "model_family": "cloud",
            "model_alias": "o3",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-fable-5",
            "model_name": "claude-fable-5",
            "model_family": "cloud",
            "model_alias": "claude-fable-5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-opus-4-8",
            "model_name": "claude-opus-4-8",
            "model_family": "cloud",
            "model_alias": "claude-opus-4.8",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-opus-4-7",
            "model_name": "claude-opus-4-7",
            "model_family": "cloud",
            "model_alias": "claude-opus-4.7",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-opus-4-6",
            "model_name": "claude-opus-4-6",
            "model_family": "cloud",
            "model_alias": "claude-opus-4.6",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-sonnet-5",
            "model_name": "claude-sonnet-5",
            "model_family": "cloud",
            "model_alias": "claude-sonnet-5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-sonnet-4-6",
            "model_name": "claude-sonnet-4-6",
            "model_family": "cloud",
            "model_alias": "claude-sonnet-4.6",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-sonnet-4-5",
            "model_name": "claude-sonnet-4-5",
            "model_family": "cloud",
            "model_alias": "claude-sonnet-4.5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-haiku-4-5-20251001",
            "model_name": "claude-haiku-4-5-20251001",
            "model_family": "cloud",
            "model_alias": "claude-haiku-4.5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
    ]


def create_model_client_registry() -> dict[str, Any]:
    return {
        "kind": MODEL_CLIENT_REGISTRY_KIND,
        "schema_version": MODEL_CLIENT_REGISTRY_SCHEMA_VERSION,
        "registry_name": "passive_model_client_registry",
        "registry_state": "RECORDED_ONLY",
        "current_state": "DISABLED",
        "executes_model": False,
        "grants_authority": False,
        "requires_human_promotion_for_execution": True,
        "clients": _default_client_records(),
        "governance": {
            "model_execution": "DISABLED",
            "runtime_execution": "DISABLED",
            "network_calls": "DISABLED",
            "shell_execution": "DISABLED",
            "provider_calls": "DISABLED",
            "artifact_is_authority": False,
            "enabled_implies_authority": False,
            "core_workbench_coupling": "NONE",
        },
    }


def dumps_model_client_registry(registry: dict[str, Any]) -> str:
    return json_lib.dumps(registry, indent=2, sort_keys=True) + "\n"


def write_model_client_registry(registry: dict[str, Any], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(dumps_model_client_registry(registry), encoding="utf-8")


def _validate_secret_ref_names(names: Any, field: str) -> list[str]:
    errors: list[str] = []
    if not isinstance(names, list):
        return [f"{field} must be a list of secret ref names"]
    for idx, name in enumerate(names):
        if not isinstance(name, str) or not name:
            errors.append(f"{field}[{idx}] must be a non-empty string")
            continue
        lower = name.lower()
        if any(lower.startswith(prefix) for prefix in ("sk-", "gsk_", "aiza", "bearer ", "key-", "secret-", "token-")):
            errors.append(f"{field}[{idx}] rejected: appears to contain a raw secret value prefix")
        elif " " in name or len(name) > 64:
            errors.append(f"{field}[{idx}] rejected: must be an environment ref name, not a raw value or passphrase")
        elif not _REF_NAME_RE.match(name):
            errors.append(f"{field}[{idx}] rejected: must follow UPPERCASE_REF syntax (e.g. OPENAI_API_KEY_REF)")
    return errors


def _validate_client_record(record: Any, index: int) -> list[str]:
    errors: list[str] = []
    field_prefix = f"clients[{index}]"
    if not isinstance(record, dict):
        return [f"{field_prefix} must be an object"]

    for forbidden_key in ("secrets", "api_key", "credentials", "token", "password"):
        if forbidden_key in record:
            errors.append(f"{field_prefix} must not contain forbidden secret or credential field '{forbidden_key}'")

    provider_id = record.get("provider_id")
    if provider_id not in KNOWN_PROVIDER_IDS:
        errors.append(f"{field_prefix}.provider_id '{provider_id}' is unknown")

    client_id = record.get("client_id")
    if client_id not in KNOWN_CLIENT_IDS:
        errors.append(f"{field_prefix}.client_id '{client_id}' is unknown")

    model_id = record.get("model_id")
    if model_id not in KNOWN_MODEL_IDS:
        errors.append(f"{field_prefix}.model_id '{model_id}' is unknown")

    endpoint_kind = record.get("endpoint_kind")
    if endpoint_kind not in ALLOWED_ENDPOINT_KINDS:
        errors.append(f"{field_prefix}.endpoint_kind '{endpoint_kind}' must be one of {sorted(ALLOWED_ENDPOINT_KINDS)}")

    risk = record.get("risk_classification")
    if not risk or risk not in ALLOWED_RISK_CLASSIFICATIONS:
        errors.append(
            f"{field_prefix}.risk_classification is missing or invalid; must be one of {sorted(ALLOWED_RISK_CLASSIFICATIONS)}"
        )

    cost = record.get("cost_class")
    if not cost or cost not in ALLOWED_COST_CLASSES:
        errors.append(f"{field_prefix}.cost_class is missing or invalid; must be one of {sorted(ALLOWED_COST_CLASSES)}")

    model_alias = record.get("model_alias")
    if model_alias is not None and model_alias not in MODEL_ALIASES:
        errors.append(f"{field_prefix}.model_alias '{model_alias}' is not a known model alias")

    for str_field in ("provider_name", "client_name", "model_name", "model_family"):
        if not isinstance(record.get(str_field), str) or not record[str_field]:
            errors.append(f"{field_prefix}.{str_field} must be a non-empty string")

    for bool_field in ("structured_output_supported", "tool_use_supported", "multimodal_supported", "enabled"):
        if not isinstance(record.get(bool_field), bool):
            errors.append(f"{field_prefix}.{bool_field} must be a boolean")

    if record.get("executes_model") is not False:
        errors.append(f"{field_prefix}.executes_model must be false or NOT_AUTHORIZED")
    if record.get("grants_authority") is not False:
        errors.append(f"{field_prefix}.grants_authority must be false or NOT_AUTHORIZED")
    if record.get("requires_human_promotion_for_execution") is not True:
        errors.append(f"{field_prefix}.requires_human_promotion_for_execution must be true")

    errors.extend(_validate_secret_ref_names(record.get("secret_ref_names"), f"{field_prefix}.secret_ref_names"))

    if not isinstance(record.get("price_metadata"), dict):
        errors.append(f"{field_prefix}.price_metadata must be an object")

    return errors


def validate_model_client_registry(record: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(record, dict):
        return ["model client registry must be a JSON object"]
    if record.get("kind") != MODEL_CLIENT_REGISTRY_KIND:
        errors.append(f"kind must be {MODEL_CLIENT_REGISTRY_KIND}")
    if record.get("schema_version") != MODEL_CLIENT_REGISTRY_SCHEMA_VERSION:
        errors.append(f"schema_version must be {MODEL_CLIENT_REGISTRY_SCHEMA_VERSION}")
    if record.get("registry_state") != "RECORDED_ONLY":
        errors.append("registry_state must be RECORDED_ONLY")
    if record.get("current_state") != "DISABLED":
        errors.append("current_state must be DISABLED or NOT_AUTHORIZED")
    if record.get("executes_model") is not False:
        errors.append("executes_model must be false or NOT_AUTHORIZED")
    if record.get("grants_authority") is not False:
        errors.append("grants_authority must be false or NOT_AUTHORIZED")
    if record.get("requires_human_promotion_for_execution") is not True:
        errors.append("requires_human_promotion_for_execution must be true")

    for forbidden_key in ("secrets", "api_key", "credentials", "token", "password"):
        if forbidden_key in record:
            errors.append(f"registry must not contain forbidden secret or credential field '{forbidden_key}'")

    clients = record.get("clients")
    if not isinstance(clients, list) or not clients:
        errors.append("clients must be a non-empty list")
    else:
        for idx, client in enumerate(clients):
            errors.extend(_validate_client_record(client, idx))

    governance = record.get("governance")
    if not isinstance(governance, dict):
        errors.append("governance must be an object")
    else:
        for key in ("model_execution", "runtime_execution", "network_calls", "shell_execution", "provider_calls"):
            if governance.get(key) != "DISABLED":
                errors.append(f"governance.{key} must be DISABLED or NOT_AUTHORIZED")
        if governance.get("artifact_is_authority") is not False:
            errors.append("governance.artifact_is_authority must be false or NOT_AUTHORIZED")
        if governance.get("enabled_implies_authority") is not False:
            errors.append("governance.enabled_implies_authority must be false or NOT_AUTHORIZED")
        if governance.get("core_workbench_coupling") != "NONE":
            errors.append("governance.core_workbench_coupling must be NONE or NOT_AUTHORIZED")

    def _check_no_active_states(obj: Any, path: str) -> None:
        if isinstance(obj, dict):
            for k, v in obj.items():
                if k in {"registry_state", "current_state", "enabled"}:
                    continue
                _check_no_active_states(v, f"{path}.{k}" if path else k)
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                _check_no_active_states(v, f"{path}[{i}]")
        elif isinstance(obj, str):
            if obj in {"EXECUTED", "AUTHORIZED", "PROMOTED", "ENABLED"}:
                errors.append(f"field '{path}' claims active authority state '{obj}'")

    _check_no_active_states(record, "registry")

    return errors


def validate_model_client_registry_file(path: Path) -> list[str]:
    if not path.exists():
        return [f"file not found: {path}"]
    try:
        data = json_lib.loads(path.read_text(encoding="utf-8"))
    except json_lib.JSONDecodeError as exc:
        return [f"invalid JSON: {exc}"]
    except Exception as exc:
        return [f"failed to read file: {exc}"]
    return validate_model_client_registry(data)


def _default_client_records() -> list[dict]:
    return [
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/Phi-4-mini-reasoning-4bit",
            "model_name": "Phi-4-mini-reasoning-4bit",
            "model_family": "local_mlx",
            "model_alias": "phi-reasoning",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/Qwen2.5-Coder-7B-Instruct-4bit",
            "model_name": "Qwen2.5-Coder-7B-Instruct-4bit",
            "model_family": "local_mlx",
            "model_alias": "qwen-coder",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/gemma-4-e4b-it-4bit",
            "model_name": "gemma-4-e4b-it-4bit",
            "model_family": "local_mlx",
            "model_alias": "gemma-fast",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/gemma-4-12B-it-4bit",
            "model_name": "gemma-4-12B-it-4bit",
            "model_family": "local_mlx",
            "model_alias": "gemma-primary",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/Meta-Llama-3.1-8B-Instruct-4bit",
            "model_name": "Meta-Llama-3.1-8B-Instruct-4bit",
            "model_family": "local_mlx",
            "model_alias": "llama",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/codegeex4-all-9b-4bit",
            "model_name": "codegeex4-all-9b-4bit",
            "model_family": "local_mlx",
            "model_alias": "codegeex",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/Qwen2.5-Coder-14B-Instruct-4bit",
            "model_name": "Qwen2.5-Coder-14B-Instruct-4bit",
            "model_family": "local_mlx",
            "model_alias": "qwen-coder-14b",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/Qwen3-Coder-30B-A3B-Instruct-4bit",
            "model_name": "Qwen3-Coder-30B-A3B-Instruct-4bit",
            "model_family": "local_mlx",
            "model_alias": "qwen3-coder-heavy",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "mlx_provider",
            "provider_name": "Local MLX Hub Provider",
            "client_id": "mlx_lm_client",
            "client_name": "MLX Language Model Client",
            "endpoint_kind": "local_mlx",
            "model_id": "mlx-community/DeepSeek-Coder-V2-Lite-Instruct-4bit",
            "model_name": "DeepSeek-Coder-V2-Lite-Instruct-4bit",
            "model_family": "local_mlx",
            "model_alias": "deepseek",
            "context_window": 16384,
            "max_input_tokens": 12288,
            "max_output_tokens": 4096,
            "structured_output_supported": False,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "llama-3.3-70b-versatile",
            "model_name": "llama-3.3-70b-versatile",
            "model_family": "cloud",
            "model_alias": "groq-llama",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "mixtral-8x7b-32768",
            "model_name": "mixtral-8x7b-32768",
            "model_family": "cloud",
            "model_alias": "groq-mixtral",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-2-1212",
            "model_name": "grok-2-1212",
            "model_family": "cloud",
            "model_alias": "grok-reasoning",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-beta",
            "model_name": "grok-beta",
            "model_family": "cloud",
            "model_alias": "grok-beta",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "google_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "google_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "google/gemini-1.5-pro",
            "model_name": "google/gemini-1.5-pro",
            "model_family": "cloud",
            "model_alias": "gemini-pro",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GOOGLE_VERTEX_CREDS_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "google_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "google_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "google/gemini-1.5-flash",
            "model_name": "google/gemini-1.5-flash",
            "model_family": "cloud",
            "model_alias": "gemini-flash",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GOOGLE_VERTEX_CREDS_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "google_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "google_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "google/gemini-1.0-ultra",
            "model_name": "google/gemini-1.0-ultra",
            "model_family": "cloud",
            "model_alias": "gemini-ultra",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GOOGLE_VERTEX_CREDS_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "google_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "google_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "google/gemini-3.5-flash",
            "model_name": "google/gemini-3.5-flash",
            "model_family": "cloud",
            "model_alias": "gemini-3.5-flash",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GOOGLE_VERTEX_CREDS_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "google_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "google_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "google/gemini-3.1-pro-preview",
            "model_name": "google/gemini-3.1-pro-preview",
            "model_family": "cloud",
            "model_alias": "gemini-3.1-pro",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GOOGLE_VERTEX_CREDS_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "google_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "google_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "google/gemini-3.1-flash-lite",
            "model_name": "google/gemini-3.1-flash-lite",
            "model_family": "cloud",
            "model_alias": "gemini-3.1-flash",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GOOGLE_VERTEX_CREDS_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "google_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "google_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "google/gemini-3-flash-preview",
            "model_name": "google/gemini-3-flash-preview",
            "model_family": "cloud",
            "model_alias": "gemini-3-flash",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GOOGLE_VERTEX_CREDS_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "ollama_provider",
            "provider_name": "Local Ollama Provider",
            "client_id": "ollama_client",
            "client_name": "Ollama Local Client",
            "endpoint_kind": "openai_compatible_local",
            "model_id": "gemma4:e4b",
            "model_name": "gemma4:e4b",
            "model_family": "local_ollama",
            "model_alias": "gemma4:e4b",
            "context_window": 8192,
            "max_input_tokens": 8192,
            "max_output_tokens": 4096,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "ollama_provider",
            "provider_name": "Local Ollama Provider",
            "client_id": "ollama_client",
            "client_name": "Ollama Local Client",
            "endpoint_kind": "openai_compatible_local",
            "model_id": "gemma4:e2b",
            "model_name": "gemma4:e2b",
            "model_family": "local_ollama",
            "model_alias": "gemma4:e2b",
            "context_window": 8192,
            "max_input_tokens": 8192,
            "max_output_tokens": 4096,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "ollama_provider",
            "provider_name": "Local Ollama Provider",
            "client_id": "ollama_client",
            "client_name": "Ollama Local Client",
            "endpoint_kind": "openai_compatible_local",
            "model_id": "qwen3.5:2b",
            "model_name": "qwen3.5:2b",
            "model_family": "local_ollama",
            "model_alias": "qwen3.5:2b",
            "context_window": 8192,
            "max_input_tokens": 8192,
            "max_output_tokens": 4096,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "ollama_provider",
            "provider_name": "Local Ollama Provider",
            "client_id": "ollama_client",
            "client_name": "Ollama Local Client",
            "endpoint_kind": "openai_compatible_local",
            "model_id": "qwen3.5:0.8b",
            "model_name": "qwen3.5:0.8b",
            "model_family": "local_ollama",
            "model_alias": "qwen3.5:0.8b",
            "context_window": 8192,
            "max_input_tokens": 8192,
            "max_output_tokens": 4096,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "ollama_provider",
            "provider_name": "Local Ollama Provider",
            "client_id": "ollama_client",
            "client_name": "Ollama Local Client",
            "endpoint_kind": "openai_compatible_local",
            "model_id": "ibm/granite4.1:3b",
            "model_name": "ibm/granite4.1:3b",
            "model_family": "local_ollama",
            "model_alias": "ibm/granite4.1:3b",
            "context_window": 8192,
            "max_input_tokens": 8192,
            "max_output_tokens": 4096,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "local_network",
            "cost_class": "free_local",
            "price_metadata": {"unit": "tokens", "input_cost": "free", "output_cost": "free"},
            "secret_ref_names": [],
            "enabled": True,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "llama-3.1-8b-instant",
            "model_name": "llama-3.1-8b-instant",
            "model_family": "cloud",
            "model_alias": "groq-llama-instant",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "openai/gpt-oss-20b",
            "model_name": "openai/gpt-oss-20b",
            "model_family": "cloud",
            "model_alias": "groq-gpt-oss-20b",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "meta-llama/llama-4-scout-17b-16e-instruct",
            "model_name": "meta-llama/llama-4-scout-17b-16e-instruct",
            "model_family": "cloud",
            "model_alias": "groq-llama-scout",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "openai/gpt-oss-120b",
            "model_name": "openai/gpt-oss-120b",
            "model_family": "cloud",
            "model_alias": "groq-gpt-oss-120b",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "qwen/qwen3-32b",
            "model_name": "qwen/qwen3-32b",
            "model_family": "cloud",
            "model_alias": "groq-qwen3-32b",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "groq_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "groq_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "moonshotai/kimi-k2-instruct-0905",
            "model_name": "moonshotai/kimi-k2-instruct-0905",
            "model_family": "cloud",
            "model_alias": "groq-kimi-k2",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["GROQ_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-4.3",
            "model_name": "grok-4.3",
            "model_family": "cloud",
            "model_alias": "grok-4.3",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-build-0.1",
            "model_name": "grok-build-0.1",
            "model_family": "cloud",
            "model_alias": "grok-build-0.1",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "xai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "xai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "grok-4.1-fast",
            "model_name": "grok-4.1-fast",
            "model_family": "cloud",
            "model_alias": "grok-4.1-fast",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["XAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.5",
            "model_name": "gpt-5.5",
            "model_family": "cloud",
            "model_alias": "gpt-5.5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.5-pro",
            "model_name": "gpt-5.5-pro",
            "model_family": "cloud",
            "model_alias": "gpt-5.5-pro",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.4",
            "model_name": "gpt-5.4",
            "model_family": "cloud",
            "model_alias": "gpt-5.4",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.4-mini",
            "model_name": "gpt-5.4-mini",
            "model_family": "cloud",
            "model_alias": "gpt-5.4-mini",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.4-nano",
            "model_name": "gpt-5.4-nano",
            "model_family": "cloud",
            "model_alias": "gpt-5.4-nano",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-5.3-codex",
            "model_name": "gpt-5.3-codex",
            "model_family": "cloud",
            "model_alias": "gpt-5.3-codex",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-4o",
            "model_name": "gpt-4o",
            "model_family": "cloud",
            "model_alias": "gpt-4o",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "openai_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "o3",
            "model_name": "o3",
            "model_family": "cloud",
            "model_alias": "o3",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-fable-5",
            "model_name": "claude-fable-5",
            "model_family": "cloud",
            "model_alias": "claude-fable-5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-opus-4-8",
            "model_name": "claude-opus-4-8",
            "model_family": "cloud",
            "model_alias": "claude-opus-4.8",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-opus-4-7",
            "model_name": "claude-opus-4-7",
            "model_family": "cloud",
            "model_alias": "claude-opus-4.7",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-opus-4-6",
            "model_name": "claude-opus-4-6",
            "model_family": "cloud",
            "model_alias": "claude-opus-4.6",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-sonnet-5",
            "model_name": "claude-sonnet-5",
            "model_family": "cloud",
            "model_alias": "claude-sonnet-5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-sonnet-4-6",
            "model_name": "claude-sonnet-4-6",
            "model_family": "cloud",
            "model_alias": "claude-sonnet-4.6",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-sonnet-4-5",
            "model_name": "claude-sonnet-4-5",
            "model_family": "cloud",
            "model_alias": "claude-sonnet-4.5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "anthropic_provider",
            "provider_name": "Cloud API Provider",
            "client_id": "anthropic_client",
            "client_name": "Cloud HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "claude-haiku-4-5-20251001",
            "model_name": "claude-haiku-4-5-20251001",
            "model_family": "cloud",
            "model_alias": "claude-haiku-4.5",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 8192,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": False,
            "risk_classification": "cloud_external",
            "cost_class": "medium",
            "price_metadata": {"unit": "million_tokens", "input_cost": "medium", "output_cost": "medium"},
            "secret_ref_names": ["ANTHROPIC_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
        {
            "provider_id": "openai_stub_provider",
            "provider_name": "OpenAI Stub Provider",
            "client_id": "openai_compat_client",
            "client_name": "OpenAI Compatible HTTP Client",
            "endpoint_kind": "openai_compatible_cloud",
            "model_id": "gpt-4o-stub",
            "model_name": "GPT 4 Omni Stub",
            "model_family": "cloud",
            "model_alias": "gpt-4o",
            "context_window": 128000,
            "max_input_tokens": 128000,
            "max_output_tokens": 4096,
            "structured_output_supported": True,
            "tool_use_supported": True,
            "multimodal_supported": True,
            "risk_classification": "cloud_external",
            "cost_class": "high",
            "price_metadata": {"unit": "million_tokens", "input_cost": "5.00", "output_cost": "15.00"},
            "secret_ref_names": ["OPENAI_API_KEY_REF"],
            "enabled": False,
            "executes_model": False,
            "grants_authority": False,
            "requires_human_promotion_for_execution": True,
        },
    ]
