from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from typing import Literal

ToolTier = Literal["tier1", "tier2", "notes"]
ToolStatus = Literal["installed", "missing", "optional-ui"]


@dataclass(frozen=True)
class ExternalTool:
    name: str
    command: str | None
    tier: ToolTier
    category: str
    role: str
    install: str
    required: bool = False
    integration: str = "detect-only"
    open_source: bool = True


@dataclass(frozen=True)
class ToolCheck:
    tool: ExternalTool
    status: ToolStatus
    version: str | None
    path: str | None


TOOLS: tuple[ExternalTool, ...] = (
    ExternalTool("repomix", "repomix", "tier1", "context", "Pack repositories into AI-friendly context files.", "brew install repomix  # or: npm install -g repomix", required=True, integration="context-pack"),
    ExternalTool("serena", "serena", "tier1", "semantic", "MCP semantic code retrieval/editing toolkit; start read-only.", "uvx --from git+https://github.com/oraios/serena serena", integration="semantic-readonly"),
    ExternalTool("semgrep", "semgrep", "tier1", "static-analysis", "Structural/static policy scans and CORE invariant rules.", "brew install semgrep  # or: pipx install semgrep", required=True, integration="scan"),
    ExternalTool("ruff", "ruff", "tier1", "quality", "Fast Python lint and format gate.", "uv tool install ruff  # or: brew install ruff", required=True, integration="quality-gate"),
    ExternalTool("pyright", "pyright", "tier1", "quality", "Python static type checking.", "npm install -g pyright  # or: brew install pyright", integration="quality-gate"),
    ExternalTool("pre-commit", "pre-commit", "tier1", "git", "Git hook orchestration for lint/type/scan/test gates.", "uv tool install pre-commit  # or: brew install pre-commit", integration="git-hooks"),
    ExternalTool("rg", "rg", "tier1", "search", "Fast ripgrep search for task-scoped file selection.", "brew install ripgrep", required=True, integration="repo-map"),
    ExternalTool("fd", "fd", "tier1", "search", "Fast file discovery for maps and context selection.", "brew install fd", integration="repo-map"),
    ExternalTool("aider", "aider", "tier2", "agent-benchmark", "AI pair-programming reference lane and benchmark target.", "uv tool install aider-chat  # or: pipx install aider-chat", integration="benchmark-only"),
    ExternalTool("ast-grep", "ast-grep", "tier2", "structural-search", "AST-based structural search, lint, and rewrite preview.", "brew install ast-grep", integration="structural-search"),
    ExternalTool("promptfoo", "promptfoo", "tier2", "prompt-eval", "Prompt, agent, and RAG evals/red-team tests.", "npm install -g promptfoo", integration="prompt-eval"),
    ExternalTool("gh", "gh", "tier2", "git", "GitHub CLI for PR/status/release workflows.", "brew install gh", required=True, integration="git-pr"),
    ExternalTool("markdown-vault", None, "notes", "knowledge-base", "Default notes backend: plain Markdown files generated by builder-II.", "No install needed.", required=True, integration="markdown-vault"),
    ExternalTool("logseq", "logseq", "notes", "knowledge-base", "Open-source Markdown/org knowledge base UI for the vault.", "brew install --cask logseq", integration="markdown-vault"),
    ExternalTool("zettlr", "zettlr", "notes", "knowledge-base", "Open-source Markdown editor suitable for lightweight documentation and Zettelkasten notes.", "brew install --cask zettlr", integration="markdown-vault"),
    ExternalTool("foam", None, "notes", "knowledge-base", "Open-source VS Code Markdown knowledge-base workflow.", "Use the Foam VS Code extension if desired.", integration="markdown-vault"),
    ExternalTool("obsidian", None, "notes", "knowledge-base", "Optional proprietary Markdown vault UI. Not a core dependency.", "Install Obsidian manually only if desired.", integration="markdown-vault", open_source=False),
)


def tool_registry() -> tuple[ExternalTool, ...]:
    return TOOLS


def tools_by_tier(tier: ToolTier) -> tuple[ExternalTool, ...]:
    return tuple(tool for tool in TOOLS if tool.tier == tier)


def _version_for(command: str) -> str | None:
    probes = ([command, "--version"], [command, "version"])
    for probe in probes:
        try:
            proc = subprocess.run(probe, capture_output=True, text=True, timeout=5)
        except (OSError, subprocess.SubprocessError):
            continue
        text = (proc.stdout or proc.stderr).strip().splitlines()
        if proc.returncode == 0 and text:
            return text[0]
    return None


def check_tool(tool: ExternalTool) -> ToolCheck:
    if tool.command is None:
        status: ToolStatus = "optional-ui" if not tool.required else "installed"
        return ToolCheck(tool, status, None, None)
    path = shutil.which(tool.command)
    if not path:
        return ToolCheck(tool, "missing", None, None)
    return ToolCheck(tool, "installed", _version_for(tool.command), path)


def check_tools(*, tier: ToolTier | None = None) -> tuple[ToolCheck, ...]:
    tools = tools_by_tier(tier) if tier else TOOLS
    return tuple(check_tool(tool) for tool in tools)


def missing_required_tools() -> tuple[ToolCheck, ...]:
    return tuple(check for check in check_tools() if check.tool.required and check.status == "missing")
